import Head from "next/head";
import type { NextPage } from "next";
import { useRouter } from "next/router";
import Container from "../../components/Layout/Container";

const JoinGameWithId: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <div>
      <Head>
        <title>Join Game Lobby</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='p-9'>
        <Container left={<h1>hello</h1>} right={<h1>hello</h1>}>
          <h1>Join Game Lobby {id}</h1>
        </Container>
      </main>
    </div>
  );
};

export default JoinGameWithId;
