import React, { useEffect } from "react";
import Head from "next/head";
import type { NextPage } from "next";
import Container from "components/Layout/Container";

// panels
import GameSettingPanel from "components/GameSettingPanel/GameSettingPanel";
import PlayerGridPanel from "components/PlayerGridPanel/PlayerGridPanel";
import PlaylistSelectorPanel from "components/PlaylistSelectorPanel/PlaylistSelectorPanel";

const Join: NextPage = () => {
	return (
		<div className="bg-template">
			<Head>
				<title>Vinyl | Join Game Lobby</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container
				left={<GameSettingPanel />}
				right={<PlaylistSelectorPanel />}
			>
				<PlayerGridPanel />
			</Container>
		</div>
	);
};

export default Join;
