import Head from "next/head";
import type { NextPage } from "next";
import Container from "../../components/Layout/Container";

const Join: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Join Game Lobby</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='p-9'>
        <Container left={<h1>hello</h1>} right={<h1>hello</h1>}>
          <h1>Join Game Lobby</h1>
        </Container>
      </main>
    </div>
  );
};

export default Join;
