import Head from "next/head";
import type { NextPage } from "next";
import Container from "components/Layout/Container";
import PlayerGrid from "components/PlayerGrid/PlayerGrid";

const Join: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Join Game Lobby</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="p-9 h-screen">
				<Container left={<h1>hello</h1>} right={<h1>hello</h1>}>
					<div className="grid gap-4">
						<PlayerGrid />
					</div>
				</Container>
			</main>
		</div>
	);
};

export default Join;
