import Head from "next/head";
import type { NextPage } from "next";
import Container from "components/Layout/Container";

//panels
import MusicCanvasPanel from "components/MusicCanvasPanel/MusicCanvasPanel";
import LeaderBoardPanel from "components/LeaderBoardPanel/LeaderBoardPanel";
import ChatPanel from "components/ChatPanel/ChatPanel";

const Game: NextPage = () => {
	return (
		<div className="bg-template">
			<Head>
				<title>Vinyl | Game</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container left={<LeaderBoardPanel />} right={<ChatPanel />}>
				<MusicCanvasPanel />
			</Container>
		</div>
	);
};

export default Game;
